### ISSUE TITLE
Possible Bug : prismaObjectType throw error in TypeScript 3.5.1

### ISSUE THREAD

**Issue by NeroBlackstone** [graphql-nexus/nexus-plugin-prisma#284] opened 2019-05-31 17:36 UTC
After update to TypeScript 3.5.1, prismaObjectType throw a error.

> TS2590: Expression produces a union type that is too complex to represent.

But downgrade to 3.4.5 it works very well.

![Screenshot from 2019-06-01 01-31-22](https://user-images.githubusercontent.com/17470335/58723624-257e8280-840d-11e9-9356-31e77cc846f5.png)

That's all, I love Nexus and Prisma.    :)

**Comment by chrisdrackett** [comment] 2019-06-04 22:09
I ran into this as well. I opened an issue here: https://github.com/prisma/nexus/issues/151 but I think I'll close it as this seems like a better location for it.

**Comment by valentinbe** [comment] 2019-06-05 08:56
Having the same issue here. I tried to generate a very simple type: 
```typescript
const MessageType = prismaObjectType({
    name: "Message",
    definition(t) {
        t.prismaFields([
            "createdAt"
        ]);
    }
});
```
Which generates the same error as above: `TS2590: Expression produces a union type that is too complex to represent.`
Downgrading to typescript 3.4.5 fixes the error.

**Comment by doums** [comment] 2019-06-06 12:45
Same problem here 
![image](https://user-images.githubusercontent.com/6359431/59033765-bb7d3780-8869-11e9-910c-b5cfa4180263.png)

**Comment by iammarkps** [comment] 2019-06-18 08:34
Anyone know how to make it work with TypeScript 3.5.1 ?

**Comment by NeroBlackstone** [comment] 2019-06-18 10:02
> Anyone know how to make it work with TypeScript 3.5.1 ?

I don't know.
For now, I think we still need to use TypeScript 3.4.5

**Comment by harvey-woo** [comment] 2019-06-24 06:58
> > Anyone know how to make it work with TypeScript 3.5.1 ?
> 
> I don't know.
> For now, I think we still need to use TypeScript 3.4.5

I still cause the same error after I downgrading typescript to v3.4.5

**Comment by iammarkps** [comment] 2019-06-25 00:49
@harvey-woo Same, When I use 
```
yarn add typescript@3.4.5 -D
```

The problem still persist in the project.

**Comment by nagman** [comment] 2019-06-25 13:31
Duplicate of #291

**Comment by cryosx** [comment] 2019-07-08 01:24
Hope that fix/update comes along...

**Comment by mathia4** [comment] 2019-07-12 03:46
Workaround in the mean time: https://github.com/prisma/nexus-prisma/issues/291#issuecomment-510732707

**Comment by chaunceyau** [comment] 2019-07-12 14:00
Yes, still an issue.

**Comment by bhram** [comment] 2019-07-28 21:32
same here

**Comment by AcerFeng** [comment] 2019-09-26 03:55
This isn't best way to fix it:

```
const User = prismaObjectType({
  name: 'User',
  definition(t: any) {
    t.prismaFields([
      'id',
      'name',
      'email',
      {
        name: 'posts',
        args: [],
      }
    ])
  }
})
```

If you don't wana see the error, add `: any`.

If you wana code intellisense, delete `: any`.

Ignore my poor English.

**Comment by blackxored** [comment] 2019-09-26 15:35
Workaround seems to be to add the type to the call, like prismaObjectType<‘User’>(...)

**Comment by nagman** [comment] 2019-09-26 16:11
> Workaround seems to be to add the type to the call, like prismaObjectType<‘User’>(...)

It works! But... why??? :sweat_smile:

**Comment by darekaze** [comment] 2019-10-23 14:06
> Workaround seems to be to add the type to the call, like prismaObjectType<‘User’>(...)

Also works for me on `typescript@3.6.3`, think this is the best workaround for me

**Closed as completed** 2020-06-08 19:34 UTC
Labels: note/prisma1
