### ISSUE TITLE
Should Prisma SDK and CLI be dev dependencies?

### ISSUE THREAD

**Issue by kldzj** [graphql-nexus/nexus-plugin-prisma#776] opened 2020-08-03 14:13 UTC
I'm seeing some really large package sizes when deploying with serverless, sometimes even hitting AWS Lambda package size limits.

It seems like the issue mostly stems from `@prisma/sdk` and `@prisma/cli` being included in the serverless package, because they're not declared as dev dependencies.

Zipped size with SDK & CLI _included_: **74.12 MB**
Zipped size with SDK & CLI _excluded_: 19.45 MB

So, my question is, are `@prisma/sdk` and `@prisma/cli` needed in runtime, or could they be installed as dev dependencies? My application is running fine without these two packages.

**Comment by jasonkuhrt** [comment] 2020-08-03 16:00
The issue is that for `@nexus/schema` users bundling is not handled for you like it is in the framework. We need to document this fact and maybe some recipes to deal with it.

**Comment by jasonkuhrt** [comment] 2020-08-03 17:36
closed by https://github.com/graphql-nexus/nexus/commit/bdb8d799527a16af73a29cd0575ccd3343475238

**Closed as completed by jasonkuhrt** 2020-08-03 17:36 UTC
Labels: type/docs
