### ISSUE TITLE
"Unknown prisma-client function" for 2+ level nested fields

### ISSUE THREAD

**Issue by d2kx** [graphql-nexus/nexus-plugin-prisma#184] opened 2019-03-07 11:52 UTC
**NOTE:** Basically the same problem as https://github.com/prisma/nexus-prisma/issues/157, which should have been fixed with nexus-prisma 0.3.4

**Describe the bug**
I am basically experiencing the same as https://github.com/prisma/nexus-prisma/issues/157, but I am using MySQL 5.7. I have updated to nexus-prisma 0.3.4 and am using Prisma 1.28.0. Basically when I do Queries or Mutations that are two or more levels deep, I get an "unknown prisma-client function" error.

**To reproduce**

Example mutation:

```
mutation {
  createContentDetail(
    data: {
      name: "contentDetailName"
      subTitle: "contentDetailSubTitle"
      description: "contentDetailDescription"
      dates: {
        create: { timestampEnd: 1549756800, timestampStart: 1549832400 }
      }
      place: {
        create: {
          name: "placeName"
          coordinates: { create: { longitude: 9.971824, latitude: 53.545086 } }
          address: {
            create: {
              street: "testStreet"
              postalcode: "testPostalcode"
              city: "testCity"
            }
          }
          phone: "placePhone"
          email: "placeEmail"
          website: "placeWebsite"
          logo: "placeLogo"
          imageMain: "placeImageMain"
          images: { set: ["image1", "image2"] }
          category: { create: { name: "catName" } }
        }
      }
    }
  ) {
    id
    name
    subTitle
    description
    dates {
      timestampEnd
      timestampStart
    }
    place {
      name
      coordinates {
        latitude
        longitude
      }
      address {
        street
        postalcode
        city
      }
      phone
      email
      website
      logo
      imageMain
      images
      category {
        id
        name
      }
    }
  }
}
```

Prisma datamodel relevant parts:

```
type ContentDetail {
  id: ID! @unique
  name: String!
  subTitle: String!
  description: String!
  dates: [Date!]!
  place: [Place!]!
}

type Place {
  name: String!
  coordinates: Coordinates!
  address: Address!
  phone: String!
  email: String!
  website: String!
  logo: String!
  imageMain: String!
  images: [String]!
  category: Category!
}

type Coordinates {
  latitude: Float! @default(value: "0.0")
  longitude: Float! @default(value: "0.0")
}
```

And it throws this error, together with a part-response:

```
{
  "errors": [
    {
      "message": "Unknown prisma-client function for field Place.coordinates",
      "locations": [
        {
          "line": 13,
          "column": 7
        }
      ],
      "path": [
        "createContentDetail",
        "place",
        0,
        "coordinates"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unknown prisma-client function for field Place.coordinates",
            "    at Object.throwIfUnknownClientFunction (/var/task/node_modules/nexus-prisma/dist/throw.js:16:15)",
            "    at /var/task/node_modules/nexus-prisma/dist/resolver.js:72:17",
            "    at field.resolve (/var/task/node_modules/graphql-extensions/dist/index.js:128:26)",
            "    at resolveFieldValueOrError (/var/task/node_modules/graphql/execution/execute.js:479:18)",
            "    at resolveField (/var/task/node_modules/graphql/execution/execute.js:446:16)",
            "    at executeFields (/var/task/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/var/task/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/var/task/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeValue (/var/task/node_modules/graphql/execution/execute.js:598:12)",
            "    at completeValue (/var/task/node_modules/graphql/execution/execute.js:565:21)"
          ]
        }
      }
    }
  ],
  "data": {
    "createContentDetail": {
      "id": "cjsyk75hl0igu0930cmzgwc44",
      "name": "contentDetailName",
      "subTitle": "contentDetailSubTitle",
      "description": "contentDetailDescription",
      "dates": [
        {
          "timestampEnd": 1549756800,
          "timestampStart": 1549832400
        }
      ],
      "place": null
    }
  }
}
```

**Expected behavior**
No "unknown prisma-client function" errors

**Additional context**
Since this issue is very similar to https://github.com/prisma/nexus-prisma/issues/157 and I am just using a different database, hopefully it can be fixed or I'll find some workaround until then.

**Comment by d2kx** [comment] 2019-03-07 13:16
Update: it works if I give Place an `id: ID! @unique`, so that there are no more 2-level nested fields, but I don't think this should be necessary

**Comment by Weakky** [comment] 2019-03-08 11:02
Hey there,

This seems like a limitation of the current `prisma-client`. At the moment, the scenario mentioned would only be possible using fragments. Because you're not providing ids on two level, it's not possible to find the coordinates associated to a place without querying everything from the parent

The workaround I'm gonna propose to you is not ideal at all, but unfortunately this seems like the only way until this lands: https://github.com/prisma/rfcs/blob/new-ts-client-rfc/text/0000-new-ts-client.md

On a side note: We should probably throw a custom error message for these cases, although it doesn't seem trivial to detect

<details>
<summary>Better answer below</summary>

**Step 1**

Add a new type definition for the GraphQL type `Place`:

```ts
// types.ts
import { Place as PrismaPlace, Coordinates } from './path-to-your-prisma-client'

export type Place = PrismaPlace & { coordinates: Coordinates }
```

**Step 2**

Update `makePrismaSchema` to use that new type definition

```ts
// schema.ts

const schema = makePrismaSchema({
    ...
    typegenAutoConfig: {
      sources: [
        {
          source: path.join(__dirname, './types.ts'),
          alias: 'types',
        },
      /*{
        source: path.join(__dirname, './context.ts'),
        alias: 'ctx',
      },*/
    ],
    /*contextType: 'ctx.Context',*/
  },
})
```
**Step 3**

Override the `ContentDetail` type:

```ts
// ContentDetail.ts

export const ContentDetail = prismaObjectType({
  name: 'ContentDetail',
  definition(t) {
    t.prismaFields(['*'])

    t.field('place', {
      ...t.prismaType.place,
      resolve(root, args, ctx) {
        return ctx.prisma.contentDetail({ id: root.id }).place() // Query all fields and the coordinates
          .$fragment(`{
            name
            phone
            email
            website
            logo
            imageMain
            coordinates {
              latitude
              longitude
            }
        }`)
      },
    })
  },
})
```

**Step 4**

Override the `Place.coordinates` field

```ts
// Place.ts

export const Place = prismaObjectType({
  name: 'Place',
  definition(t) {
    t.prismaFields(['*'])

    t.field('coordinates', {
      ...t.prismaType.coordinates,
      resolve(root, args, ctx) {
        return root.coordinates // Return the coordinates passed from the parent
      },
    })
  },
})
```
</details>

**Comment by Weakky** [comment] 2019-03-08 11:54
## Update

`id` fields **are gonna be mandatory very soon** anyway as part of the datamodel v1.1. So I suggest you just use an `id` field and ignore my answer above 🙂

## Better solution

On a side note, not having `id` fields here doesn't make sense anyway. I think you're doing that because coordinates are just metadata and you won't share `Coordinates` across several `Place`.
**But your datamodel should not necessarily reflect your GraphQL schema, these are two very different things despite the fact that we're using the SDL language to do both.**

To be clearer, your `Place` record should probably look like this:

```graphql
type Place {
  name: String!
  latitude: Float! @default(value: "0.0")
  longitude: Float! @default(value: "0.0")
  ...
}
```

And, for clarity, it's indeed a good idea to separate `latitude` and `longitude` in a separate object type (but only on your GraphQL schema)

```ts
const Coordinates = objectType({
  name: 'Coordinates',
  definition(t) {
    t.float('longitude')
    t.float('latitude')
  }
})

export const Place = prismaObjectType({
  name: 'Place',
  definition(t) {
    t.prismaFields({ filter: ['latitude', 'longitude'] })
    
   t.field('coordinates', {
     type: 'Coordinates',
     resolve(root) {
       return { longitude: root.longitude, latitude: root.latitude }
     }
   })
  }
})
```

**Comment by d2kx** [comment] 2019-03-09 09:11
Thank you for both answers! I went with the id field route, but it's interesting to see how this could have been worked around aswell.

**Comment by Weakky** [comment] 2019-03-11 17:54
Awesome, closing now 🙏

**Comment by Hitabis** [comment] 2019-05-08 14:42
@Weakky could this be reopened, please?

### This is still a problem on embedded types (mongodb)

Here is a simple example (**not working**):
```

type Item {
    id: ID! @id
    subitem: SubItem
}
type SubItem @embedded {
    subSubItem: SubSubItem
}
type SubSubItem @embedded {
    withEnum: SubSubItemEnum
}
enum SubSubItemEnum {
    NEW
    OLD
}
```
Simple insert:
```
mutation {
  createItem(data: { subitem: { create: { subSubItem: {create: {withEnum: NEW }} } } }) {
    id
    subitem {
      subSubItem {
      	withEnum
      }
    }
  }
}
```
=> `"message": "Unknown prisma-client function for field SubItem.subSubItem",`


With an Id for all embedded fields (which is looking strange)
```

type Item {
    id: ID! @id
    subitem: SubItem
}
type SubItem @embedded {
    id: ID! @id
    subSubItem: SubSubItem
}
type SubSubItem @embedded {
    id: ID! @id
    withEnum: SubSubItemEnum
}
enum SubSubItemEnum {
    NEW
    OLD
}
```
=> `"message": "Unknown prisma-client function for field SubItem.subSubItem",`

with @unique it tells me
```
  SubItem
    ✖ The field `id` is marked as unique but its type `SubItem` is embedded. This is disallowed.
```

**Comment by Weakky** [comment] 2019-05-16 09:47
Hey there,

This issue is related to two things:

1. You probably did not add `databaseType: document` to your datamodel.prisma file https://www.prisma.io/docs/prisma-cli-and-configuration/prisma-yml-5cy7/#databasetype-optional. This is needed for nexus-prisma to know about embedded types
2. https://github.com/prisma/prisma/issues/4443. There's currently an issue with the client not properly fetching the embedded fields as expected.

Once the two are fixed, things should work properly again 🙏

**Comment by Hitabis** [comment] 2019-05-16 13:34
OK thanks.
It's working with `databaseType: document`with and without Id.

**Comment by aurelien-clu** [comment] 2019-06-08 15:31
Hello,

I have a similar issue but with a relational model, using PostgreSQL.
The model may be a bit tricky and not done as it should be :innocent: (feel free to criticize)

Using `prisma`, I am able to save and fetch data.
Using `GraphQL shield` I cannot retrieve the nested fields.
Am I forgetting something obvious like enabling some types to be queried? 
I tried adding a `MyObject.ts`, `SubOjbect.ts` and `KeyValue.ts` to the `resolvers` dir but without success. (note: I don't have a `Javascript` background, I know `Scala` and `Python`)

The example my code is based on: [prisma-examples/typescript/graphql-auth](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-auth)

```graphql
query {
  roots(last: 10) {
    id
    my_object {
      id
      field0 {
        my_dict { key value }
      }
      field1 {
        my_dict { key value }
      }
    }
  }
}
```

> "message": "Unknown prisma-client function for field MyObject.field0"
> "message": "Unknown prisma-client function for field MyObject.field1"

<edit start>

```
graphql_shield_1_b46845fa431f | Error: Unknown prisma-client function for field MyObject.field0
graphql_shield_1_b46845fa431f |     at Object.throwIfUnknownClientFunction (/app/node_modules/nexus-prisma/src/throw.ts:30:11)
graphql_shield_1_b46845fa431f |     at /app/node_modules/nexus-prisma/src/resolver.ts:119:5
graphql_shield_1_b46845fa431f |     at /app/node_modules/graphql-middleware/src/applicator.ts:34:9
graphql_shield_1_b46845fa431f |     at /app/node_modules/graphql-shield/src/generator.ts:60:16
graphql_shield_1_b46845fa431f |     at Generator.next (<anonymous>)
graphql_shield_1_b46845fa431f |     at fulfilled (/app/node_modules/graphql-shield/dist/generator.js:4:58)
graphql_shield_1_b46845fa431f |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

<edit end>


With the following `datamodel`:

```graphql
type Root {
  id: ID! @id
  my_object: MyObject
}

type MyObject {
  id: ID! @id
  field0: [SubOjbect] @relation(name: "F0Relation")
  field1: [SubOjbect] @relation(name: "F1Relation")
}

SubOjbect {
  id: ID! @id!
  my_object_f0: MyObject @relation(name: "F0Relation")
  my_object_f1: MyObject @relation(name: "F1Relation")
  my_dict: [KeyValue] @scalarList(strategy: RELATION)
}

type KeyValue {
  id: ID! @id
  key: String
  value: String
}
```

I use basic permissions in `permissions/index.ts`:

```javascript
import { rule, shield } from 'graphql-shield'
import { getUserId } from '../utils'

const rules = {
  isAuthenticatedUser: rule()((parent, args, context) => {
    const userId = getUserId(context)
    return Boolean(userId)
  }),
}

export const permissions = shield({
  Query: {
    me: rules.isAuthenticatedUser,
    root: rules.isAuthenticatedUser,
    roots: rules.isAuthenticatedUser,
  }
}, { debug: true }
)
```

Sorry for the long post, I hope it is not too detailed but as detailed as possible :smile:

**Comment by aurelien-clu** [comment] 2019-06-08 15:41
Actually I ended up starting this at the `mongo` post, I will investigate previous post, sorry my message may be useless :disappointed:

**Comment by aurelien-clu** [comment] 2019-06-10 08:17
Well actually I am not managing to make it work.
Below are failed attempts:

```typescript
import { prismaObjectType } from 'nexus-prisma'

export const MyObject = prismaObjectType({
  name: 'MyObject',
  definition(t) {
      t.prismaFields([ 'id' ])
      t.list.field('field0', {
        type: 'SubOjbect',
        resolve(root) {
          return { field0: root.field0 }
        }
      })
    },
})
```

```typescript
import { prismaObjectType } from 'nexus-prisma'

export const MyObject = prismaObjectType({
  name: 'MyObject',
  definition(t) {
      t.prismaFields([ 'id' ])
      t.list.field('field0', {
        type: 'SubOjbect',
        resolve(root) {
          return root.field0
        }
      })
    },
})
```

```graphql
type MyObject {
  id: ID! @id
  field0: [SubOjbect]! @relation(name: "F0Relation")
  field1: [SubOjbect]! @relation(name: "F1Relation")
}
```

**Comment by tafelito** [comment] 2019-09-04 21:32
what about when trying to query the count aggregation?

if you try to do 
```js
categoriesConnection {
    aggregate {
      count
    }
  }
```

it will give the same error. In this case there is no id field to query, the only field is count. Is there any workaround in this case? 

Same question [here](https://www.prisma.io/forum/t/nexus-not-expose-all-functions-not-able-to-call-aggregation-from-nexus-interface/7543) 

**UPDATE**
I found that by doing this it works, but of course is an overhead and it shouldn't be like that

```js
export const Query = prismaObjectType({
  name: "Query",
  definition(t) {
    t.field("categoriesConnection", {
      ...t.prismaType.categoriesConnection,
      resolve: async (_, args, { prisma }) => {
        // FIXME: Fix types https://github.com/prisma/nexus-prisma/issues/370
        // @ts-ignore
        const cc = await prisma.categoriesConnection(args);
        // @ts-ignore
        const aggregate = await prisma.categoriesConnection(args).aggregate();
        const connection = {
          ...cc,
          aggregate: {
            ...aggregate,
          },
        };
        return connection;
      },
    });
  },
});

export const CategoryConnection = prismaObjectType({
  name: "CategoryConnection",
  definition(t) {
    t.prismaFields({ filter: ["aggregate"] });

    t.field("aggregate", {
      type: "AggregateCategory",
      resolve(root) {
        return {
          // @ts-ignore
          ...root.aggregate,
        };
      },
    });
  },
});
```

I'm not sure if the problem is that the aggregate function is a promise that is only present in the connection promise itself, not in the resolved value

**Closed as completed** 2020-06-08 19:34 UTC
Labels: note/prisma1
