### ISSUE TITLE
Generated code should include docs/examples

### ISSUE THREAD

**Issue by schickling** [graphql-nexus/nexus-plugin-prisma#475] opened 2019-10-13 15:07 UTC
Currently using the generated code (besides the types) isn't very approachable. One way to make it more approachable I'd suggest to include code comments in the generated code incl. docs and examples.

![image](https://user-images.githubusercontent.com/1567498/66717675-faa13380-eddb-11e9-804e-09cbdb3d5cb7.png)

**Comment by Weakky** [comment] 2019-10-15 09:21
This is a duplicate of #310, closing

**Closed as completed by Weakky** 2019-10-15 09:21 UTC
Labels: note/duplicate
