### ISSUE TITLE
Naming convention for c.curd.[modelName]()

### ISSUE THREAD

**Issue by Albert-Gao** [graphql-nexus/nexus-plugin-prisma#557] opened 2019-12-09 21:42 UTC
Sorry for being pedantic here.

```javascript
    t.crud.post()

    t.crud.createPost()
    t.crud.updatePost()
    t.crud.updateManyPost()
    t.crud.upsertPost()
    t.crud.deletePost()
    t.crud.deleteManyPost()
```

Can we change the name of `t.crud.post()` to ` t.crud.readPost()`?

So, 
1. it can align with the rest `crud` convention
1. to make it look more like a real action rather than a model,  otherwise, `t.crud.post.read()` or ``t.crud.post.create()`` seems to be a more intuitive API.

Thanks 😛

**Comment by thehappycoder** [comment] 2019-12-26 22:15
I vote for keeping `post` and `posts` for queries. But if needs to change, `getPost` and `getPosts` seems better to me.

**Comment by jasonkuhrt** [comment] 2019-12-30 19:29
Duplicate of https://github.com/prisma-labs/nexus-prisma/issues/491. Please bring your ideas/feedback there 🙌

**Closed as completed by jasonkuhrt** 2019-12-30 19:29 UTC
Labels: note/duplicate, type/feat
