### ISSUE TITLE
Enums not working properly

### ISSUE THREAD

**Issue by malekjaroslav** [graphql-nexus/nexus-plugin-prisma#361] opened 2019-08-20 19:51 UTC
**Version**: prisma2@2.0.0-alpha.119

When using enums and querying  it, it throws an error `photon[mapping.plural].findOne(...)[graphqlField.name] is not a function`

```
enum PricingType {
  NET
  SELLING
}

model Pricing {
  id    String      @default(cuid()) @id @unique
  type  PricingType
  adult Float
  child Float
}
```

Also types are probably not generated correctly
<img width="263" alt="Screenshot 2019-08-20 at 21 50 41" src="https://user-images.githubusercontent.com/7753942/63379468-ac038a00-c394-11e9-91ea-a3dbc52a409d.png">

**Comment by jasonkuhrt** [comment] 2019-08-22 02:06
Duplicate of #327 resolved by #353

**Closed as completed by jasonkuhrt** 2019-08-22 02:06 UTC
Labels: type/bug
