### ISSUE TITLE
Engine has already been stopped

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#340] opened 2019-07-08 09:03 UTC
Every once in a while, I get the following error message in my graphql-yoga server: 
```
Error: Error in Photon:
Engine has already been stopped
    at PhotonFetcher.<anonymous> (/Users/.../node_modules/@generated/photon/index.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/.../node_modules/@generated/photon/index.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
Restarting the graphql-yoga server solves the problem.

**Comment by Weakky** [comment] 2019-09-10 12:48
Hey everyone 👋, I cannot reproduce this issue anymore. I tried @gihrig's reproduction (by removing the yup's validation middlewares), photon does show an error, but sending a valid query again does work properly.

@pantharshit00 There's never been some code that would call `.disconnect()` when an error is thrown. Maybe something has been fixed on photon's side by then.

I'm closing for now, if someone experiences that issue again, please post a comment and I'll reopen

**Closed as completed by Weakky** 2019-09-10 12:48 UTC
Labels: type/bug

**Comment by gihrig** [comment] 2019-09-11 00:08
I can confirm: The error is not reproducible with preview-8.

I did not test with earlier versions.

I was not able to test with preview-10 due to issues with #372, but a new project created with preview-10, prisma2 init and graphql-auth example works as expected when run on the error reproduction routine above.

When I get my dev project working under preview-10, I'll post back with results.

**Comment by heymartinadams** [comment] 2019-10-29 22:44
Same error occurred for me when I had included the following to the main `index.js` file:

```js
// Begin GraphQLServer
server
  .start(options)
  .catch(e => {
    console.error(e)
  })
  .finally(async () => {
    await photon.disconnect()
  })
```

Once I removed the `photon.disconnect()`, I stopped getting this error message. Basically, an error throw already disconnects the engine, and there’s no need to explicitly disconnect it again.
