### ISSUE TITLE
Errors during transpilation

### ISSUE THREAD

**Issue by marticrespi** [graphql-nexus/nexus-plugin-prisma#120] opened 2019-02-21 07:00 UTC
When you try to transpile it throws these errors:

````
node_modules/nexus-prisma/dist/definitions/extendType.d.ts:10:151 - error TS2344: Type 'NexusExtendTypeDef<TypeName>' does not satisfy the constraint 'AllNexusNamedTypeDefs'.
  Type 'NexusExtendTypeDef<TypeName>' is not assignable to type 'NexusInputObjectTypeDef<string>'.
    Property 'config' is protected but type 'NexusExtendTypeDef<TypeName>' is not a class derived from 'NexusInputObjectTypeDef<TypeName>'.

10 export declare function prismaExtendType<TypeName extends PrismaObjectTypeNames>(typeConfig: PrismaExtendTypeConfig<TypeName>): core.NexusWrappedType<core.NexusExtendTypeDef<TypeName>>;
                                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/nexus/dist/builder.d.ts:191:6 - error TS2315: Type 'GraphQLObjectType' is not generic.

191   ): GraphQLObjectType<any, any>;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/nexus/dist/builder.d.ts:209:6 - error TS2315: Type 'GraphQLObjectType' is not generic.

209   ): GraphQLObjectType<any, any>[];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/nexus/dist/utils.d.ts:15:9 - error TS2315: Type 'GraphQLObjectType' is not generic.

15   type: GraphQLObjectType<any, any>,
````

**Comment by Weakky** [comment] 2019-02-21 09:20
Hey there,

This is a duplicate of #118. The solution can be found there 🙂

Closing now

**Closed as completed by Weakky** 2019-02-21 09:20 UTC
