### ISSUE TITLE
Type error passing a nexus generated arg type to prisma client

### ISSUE THREAD

**Issue by snake575** [graphql-nexus/nexus-plugin-prisma#719] opened 2020-06-17 20:41 UTC
Hi 👋 I encountered a ts error when passing an arg with a nexus generated `*WhereUniqueInput` type to the prisma client.

**Repro**: [snake575/nexus-prisma-arg-type-error](https://github.com/snake575/nexus-prisma-arg-type-error)

- prisma: `2.1.3`
- nexus-plugin-prisma: `0.16.1`
- @nexus/schema: `0.14.0`

`schema.prisma`

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @default(autoincrement()) @id
  email String  @unique
  name  String?
}
```

`schema.ts`

```ts
import { arg, makeSchema, objectType, queryType } from '@nexus/schema'
import { nexusSchemaPrisma } from 'nexus-plugin-prisma/schema'
import * as path from 'path'

export const schema = makeSchema({
  typegenAutoConfig: {
    contextType: '{ prisma: PrismaClient.PrismaClient }',
    sources: [{ source: '.prisma/client', alias: 'PrismaClient' }],
  },
  outputs: {
    typegen: path.join(__dirname, 'generated/nexusTypes.gen.ts'),
  },
  plugins: [
    nexusSchemaPrisma({
      experimentalCRUD: true,
    }),
  ],
  types: [
    objectType({
      name: 'User',
      definition(t) {
        t.model.id()
        t.model.email()
        t.model.name()
      },
    }),
    queryType({
      definition(t) {
        // CRUD
        t.crud.user()
        // Custom
        t.field('customUser', {
          type: 'User',
          nullable: true,
          args: {
            where: arg({ type: 'UserWhereUniqueInput', required: true }),
          },
          resolve: (_root, { where }, ctx) => {
            return ctx.prisma.user.findOne({ where })
          },
        })
      },
    }),
  ],
})
```

With `prisma <= 2.0.0-beta-5` and `nexus-prisma 0.14.0` everything works as expected.

However, since `prisma 2.0.0-beta.6` up to `prisma 2.1.3` and `nexus-plugin-prisma 0.16.1`, ts throws the following for the `where` arg on the `customUser` field on the example above.

```
Type '{ email?: string | null | undefined; id?: number | null | undefined; }' is not assignable to type 'UserWhereUniqueInput'.
  Types of property 'id' are incompatible.
    Type 'number | null | undefined' is not assignable to type 'number | undefined'.
      Type 'null' is not assignable to type 'number | undefined'.
```

![image](https://user-images.githubusercontent.com/4157289/86178258-0e213580-baf6-11ea-82b9-f128eecdc859.png)

**Comment by alizhdanov** [comment] 2020-06-18 11:12
Have the same issue. Looks like Prisma starting from `2.0.0-beta.6` changed the way of generating types for optional fields.
From `field?: type | null` to `field?: type`

**Comment by oceandrama** [comment] 2020-06-19 06:18
Can confirm it too

**Comment by maaft** [comment] 2020-06-23 14:54
Yep, can confirm too. Any workarounds?

**Comment by oceandrama** [comment] 2020-06-25 21:29
@jasonkuhrt Any updates?

**Comment by snake575** [comment] 2020-06-30 21:24
Updated the [Repro](https://github.com/snake575/nexus-prisma-arg-type-error) to `prisma 2.1.3` and `nexus-plugin-prisma 0.16.1` as the problem persists :pensive:

**Comment by jasonkuhrt** [comment] 2020-07-01 04:54
Duplicate of https://github.com/graphql-nexus/nexus/issues/1058.

Known issue, we'd like to see a solution too. Some design discussions over there.

**Closed as completed by jasonkuhrt** 2020-07-01 04:54 UTC
Labels: note/duplicate

**Comment by kfbfarley** [comment] 2021-12-08 00:30
> Duplicate of https://github.com/graphql-nexus/nexus/issues/1058.
> 
> Known issue, we'd like to see a solution too. Some design discussions over there.

Duplication is gone. The problem is still happening with me while trying to update a row based on the user_id
