### ISSUE TITLE
errors in nexus-prisma-typegen/index.d.ts with typescript@3.9.0-beta

### ISSUE THREAD

**Issue by pantharshit00** [graphql-nexus/nexus-plugin-prisma#636] opened 2020-03-30 22:11 UTC
## Bug description
I tried [TS3.9 beta ](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/). It gives some perf boost BTW.
No issues with TS3.8

There are errors in node_modules/@types/nexus-prisma-typegen/index.d.ts
<img width="663" alt="Screen Shot 2020-03-28 at 10 46 30" src="https://user-images.githubusercontent.com/5582266/77818334-a4525380-70e2-11ea-8510-51ca393e5e2d.png">
<img width="725" alt="Screen Shot 2020-03-28 at 10 45 51" src="https://user-images.githubusercontent.com/5582266/77818339-a74d4400-70e2-11ea-8f17-830c7ca62065.png">

## How to reproduce
1. yarn add -D typescript@3.9.0-beta
2. ./node_modules/.bin/prisma2 generate
3. ts-node --transpile-only src/schema
4. try to compile project or goto node_modules/@types/nexus-prisma-typegen/index.d.ts

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: "@prisma/cli": "^2.0.0-preview025"
- Node.js version: v13.7.0

**Comment by alexichepura** [comment] 2020-04-23 04:22
@pantharshit00 please close it as I can't reproduce it anymore with the latest versions of prisma and nexus. Thanks!

**Closed as completed** 2020-04-23 04:34 UTC

**Comment by peterrogov** [comment] 2020-05-15 10:50
I have exactly the same problem here. Trying to compile one of [graphql-apollo-server](https://github.com/prisma/prisma-examples/tree/master/typescript/graphql-apollo-server) example from prisma official repo and it doesn't work with typescript 3.9.2. Downgraded to typescript 3.8.3 and compilation went well.

This is how the dependencies look like:
```
  "dependencies": {
    "@nexus/schema": "0.13.1",
    "@prisma/client": "2.0.0-beta.5",
    "@types/node-fetch": "2.5.7",
    "apollo-server": "2.13.1",
    "graphql": "14.6.0",
    "nexus-prisma": "0.12.0"
  },
  "devDependencies": {
    "@prisma/cli": "2.0.0-beta.5",
    "@types/node": "12.12.39",
    "ts-node": "8.10.1",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.9.2"
  },
```

changing to 
```
    "typescript": "3.8.3"
```

without any other changes to packages or code allows building without errors
