### ISSUE TITLE
Possibility to specify model just once?

### ISSUE THREAD

**Issue by heymartinadams** [graphql-nexus/nexus-plugin-prisma#317] opened 2019-06-28 15:49 UTC
Currently, in `project.prisma` (or `schema.prisma` if that naming convention gets implemented), we specify the datamodel, like so:

```graphql
model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  author    User?
  content   String?
  published Boolean
  title     String
}
```

Then, in `/src/index.js` we specify it again, albeit in a different form, like so:

```javascript
const Post = objectType({
  name: 'Post',
  definition(t) {
    t.model.id()
    t.model.createdAt()
    t.model.updatedAt()
    t.model.author()
    t.model.title()
    t.model.content()
    t.model.published()
  },
})
```

I get that that’s necessary, just wondering if there’s a way — call me lazy — we can avoid needing to re-specify the model as it gets built out.

**Comment by schickling** [comment] 2019-06-28 16:41
Thanks a lot for bringing this up @heymartinadams. Would the following be a good solution for your problem?

```ts
const Post = objectType({
  name: 'Post',
  definition(t) {
    // dangerously expose all model fields (incl. relations)
    t.model._allFields()
  },
})
```

**Comment by heymartinadams** [comment] 2019-06-28 17:56
Great, thanks @schickling! Though why “dangerously”? (question no doubt exposes my neophyte status).

Might it be because some relations (one to many) [require certain resolvers](https://nexus.js.org/docs/api-objecttype)? e.g. if `User` has a one-to-many relation to `Post`:
```js
const User = objectType({
  name: "User",
  definition(t) {
    t.int("id", { description: "Id of the user" })
    t.string("fullName", { description: "Full name of the user" })
    t.field("status", "StatusEnum")
    t.list.field("posts", {
      type: Post, // or "Post"
      resolve(root, args, ctx) {
        return ctx.getUser(root.id).posts()
      }
    })
  }
})
```

**Comment by Hebilicious** [comment] 2019-07-09 13:33
What about the ability to do this in the following way:
```
const nexusPrisma = nexusPrismaPlugin({
  photon: (ctx: Context) => ctx.photon,
  models: ["*"],
  models: ["User"],
  models: {select: ["User", "Post"]},
  models: {exclude: ["Post"]}
});
```
With of course the possibility to define a custom User type that would over-ride those ones if merged in the typeDefs.

**Comment by Weakky** [comment] 2019-09-21 07:21
This is a duplicate of #299. If you think it's different than #299, we'll re-open 🙏

**Closed as completed by Weakky** 2019-09-21 07:21 UTC
Labels: note/duplicate, type/feat, scope/projecting
